version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: laravel_advanced
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  db:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel_advanced
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-volumes-data/db:/var/lib/mysql
      - ./docker/mysql/sql.cnf:/etc/mysql/sql.cnf
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "3308:80"
    environment:
      PMA_HOST: db
      MYSQL_DATABASE: laravel_advanced
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1000000K
      MAX_EXECUTION_TIME: 3600
    networks:
      - app-network
  redis:
    image: redis
    volumes:
      - ./docker-volumes-data/redis:/data
    ports:
      - "6380:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
